### ISSUE TITLE
Verify parsing, some creatures have null or empty names

### ISSUE THREAD

**Issue by Tschis** [Galarzaa90/tibiawiki-sql#7]
## Null or empty names exist at the moment:

There seems to be code to prevent non-existing 'actualname' in the returned JSON, but there are still some cases (173 null and 11 empty names):

- SQL:
  `select count(*), name from creatures where name is null or name = '' group by name;`
- Result:
  ![image](https://user-images.githubusercontent.com/20662669/32663323-bf0644fa-c614-11e7-8aa1-5f2416f9bf62.png)

### Null names
If you check creatures with null names and call the wikia API, you can see the name returned in the JSON.
For example, Arthei has a null name but his API call returns a JSON which contains his name:
- SQL: 
  `select id, name, title from creatures where title = 'Arthei';`
- API call [here](http://tibia.wikia.com/api.php?action=query&titles=Arthei&prop=revisions&rvprop=content&format=jsonfm)
- Slice of the returned JSON:
  - Notice there is no 'actualname' attribute;
  `{{Infobox Creature|List={{{1|}}}|GetValue={{{GetValue|}}}\n| name           = Arthei\n|`

### Empty names
Same is true if you check creatures with empty names. For example, Anomaly has an empty name.

- SQL: 
  `select id, name, title from creatures where name = 'Anomaly';`
- API call [here](http://tibia.wikia.com/api.php?action=query&titles=Anomaly&prop=revisions&rvprop=content&format=jsonfm)
- Slice of the returned JSON:
  - Notice there is an empty 'actualname' attribute;
  `""{{Infobox Creature|List={{{1|}}}|GetValue={{{GetValue|}}}\n| name           = Anomaly\n| article        = \n| actualname     = \n|`

**Comment by Galarzaa90** [comment]
This is something that requires a lot of attention, because if there's no consistency in the field's names, implementation becomes really difficult.

A step towards it is to rewrite the [`parse_attributes`](https://github.com/Galarzaa90/tibiawiki-sql/blob/master/utils/parsers.py#L82) function. If an attribute is empty, just leave it out of the dictionary. TibiaWiki usually leaves a lot of attributes empty to easily fill out later, as you can see in Anomaly's response. This makes it even more complicated to check if a attribute is set or not, because on top of checking if an attribute exists, you have to check if it's not empty or just a whitespace, adding more boiler plate.

Another step towards this is taking advantage of SQLite's default values, set default values where needed and do not insert a value there if it's not present.

**Comment by Galarzaa90** [comment]
Commit 54ad0a3 should fix this issue, but I will leave this open until I implement the same parsing to other tables.

**Comment by Galarzaa90** [comment]
The parsing for all other tables has been checked and fixed.
